return {}
-- return {
--   'rmagatti/auto-session',
--   lazy = false,
--
--   ---enables autocomplete for opts
--   ---@module "auto-session"
--   ---@type AutoSession.Config
--   opts = {
--     suppressed_dirs = { '~/', '~/Documents', '~/Downloads', '/', '~/Documents/Code' },
--     -- log_level = 'debug',
--   },
-- }
