# Personal Aliases
alias ntop="sudo nethogs"
alias ttp="tt -n 100 -blockcursor -json >> ~/.cache/tt.out"
alias c="wl-copy"
alias cl="fc -ln -1 | wl-copy" 
alias hot="sudo create_ap wlp2s0 wlp2s0 EDITH jarvis726"
alias pn="pnpm"
alias nv="nvim"
alias subs="subliminal download -l en *.mp4"
alias ff="fastfetch"
alias ssh="kitty +kitten ssh"
alias dy="dysk"
alias bt="btop"
alias zl="zellij"
alias zj="zellij -l simple"
alias zjd="zellij"
alias zjn="zellij -l simple attach --create"
alias oc="opencode"
