[opener]
read = [
	{ run = 'evince "$@"', orphan = true, desc = "Read", for = "linux" },
]
extract = [
	{run = 'unzip "$@"', orphan = true, desc = "Extract", for = "linux"},
]

[open]
prepend_rules = [
	{ url = "*.pdf", use = ["open", "read", "reveal"] },
	{ url = "*.zip", use = ["extract", "reveal"] },
]
